AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  buildsl

Resources:
  buildsl:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: buildsl/
      Handler: status.lambda_handler
      Runtime: python3.8
      Events:
        status:
          Type: Api
          Properties:
            Path: /status
            Method: get
        # status:
        #   Type: Api
        #   Properties:
        #     Path: /update
        #     Method: post

# Outputs:
#   HelloWorldApi:
#     Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#   HelloWorldFunction:
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt HelloWorldFunction.Arn
#   HelloWorldFunctionIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt HelloWorldFunctionRole.Arn
