AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  buildsl

Resources:
  buildsl:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./buildsl
      Handler: ops.lambda_handler
      Runtime: python3.8
      Timeout: 10
      # CodeUri: ./functions
      # Layers:
      #   - arn......
      # Policies:
      #   - DynamoCrudPolicy:
      #       TableName: !Ref GreetingsTable
      # Environment:
      #   Variables:
      #     GREETINGS_TABLE: !Ref GreetingsTable
      Events:
        ops:
          Type: Api
          Properties:
            Path: /ops
            Method: ANY
            StageName: dev
        # # update:
        #   Type: Api
        #   Properties:
        #     Path: /ops
        #     Method: POST
        #     # Auth:
        #     #   ApiKeyRequired: false
  # GreetingsTable: 
  #   Type: AWS::Serverless::SimpleTable

  # EBRule:
  #   Type: EventBridgeRule
  #   Properties:
  #     Input: '{"Key": "Value"}'
  #     Pattern:
  #       detail:
  #         state:
  #           - terminated
  #     RetryPolicy:
  #       MaximumRetryAttempts: 5
  #       MaximumEventAgeInSeconds: 900
  #     DeadLetterConfig:
  #       Type: SQS
  #       QueueLogicalId: EBRuleDLQ
  #     Target:
  #       Id: MyTarget

# Outputs:
#   HelloWorldApi:
#     Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#   HelloWorldFunction:
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt HelloWorldFunction.Arn
#   HelloWorldFunctionIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt HelloWorldFunctionRole.Arn
